sudo: required
dist: trusty

services:
- docker

language: python
python:
- "3.6"

env:
- DJANGO_SETTINGS_MODULE=conf.settings.testing

before_install:
- docker-compose pull
- docker-compose up -d redis
- docker-compose ps

script:
python manage.py test